services:
  - type: web
    name: serpent-showdown
    env: docker
    dockerFilePath: ./Dockerfile.deploy
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: serpent-db
          property: connectionString
      - key: STATIC_DIR
        value: /app/static

databases:
  - name: serpent-db
    databaseName: serpent_showdown
    user: serpent
    plan: free
